### ISSUE TITLE
The status page should link to the proposals in question

### ISSUE THREAD

**Issue by mousetail** [AssemblyScript/website#136]
So I'm reading the status page: https://github.com/AssemblyScript/website/blob/main/src/status.md / https://www.assemblyscript.org/status.html

There's a lot of things here but I have no idea what most of them mean. Even a google search doesn't tell me the meaning of "Non-trapping F2I".

If I understand correctly all elements in this table are references to proposal documents. Maybe it would help to link to the relevant proposals that explain what the feature actually does?

For example, I'm wondering "What is WASI3 and why is it controversial?". I could browse through the proposals and try to find them but ideally they should just be linked.

**Comment by dcodeIO** [comment]
I have been wondering about this as well. So far I assumed that linking to the [proposals repository](https://github.com/WebAssembly/proposals) above the table could be enough for discoverability, but I agree that it might not always be clear how to approach it. The "Non-trapping float-to-int conversions" proposal can only be found when following the "Finished Proposals" link, for example. Would be OK with linking to the proposals directly if it helps.
