### ISSUE TITLE
[Chrome] Start page example immediately failing

### ISSUE THREAD

**Issue by tristan-f-r** [AssemblyScript/website#188]
## Environment

Latest website version at the time of issue writing, `Chrome Version 108.0.5359.125 (Official Build) (64-bit)`.

I don't have the ability to replicate the issue at firefox as of now, so if anyone else can, please do so.

## Reproduce

- Go to https://www.assemblyscript.org/
- Scroll down, and click the `module.wat` tab
- Immediately get the following error:
  ```
  ;; INFO asc module.ts --textFile module.wat --outFile module.wasm --bindings raw -O3 --runtime stub
  ;; ERROR TS1012: Unexpected token.
  ;;    :
  ;;  4 │ if (n > 0) {
  ;;    │ ^
  ;;    └─ in module.ts(4,3)
  ;; 
  ;; FAILURE 1 parse error(s)
  (module
   ;; FAILURE 1 parse error(s)
  )
  ```

To fix the error, a semicolon is needed after `b = 1`.

**Comment by dcodeIO** [comment]
Relevant PR causing the issue: https://github.com/AssemblyScript/assemblyscript/pull/2252
