### ISSUE TITLE
Documentation Search Not Showing examples?

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/website#24]
For example, when I search `mandelbrot`:

![Screenshot from 2020-10-15 11-15-43](https://user-images.githubusercontent.com/1448289/96169992-d76e0000-0ed7-11eb-85ad-f3845a912cbc.png)

It doesn't show the mendelbrot tutorial. I think it'd be helpful to also search through the example page, especially for the snippets that way they are easier to find :smile:

**Comment by torch2424** [comment]
If I'm not mistaken, we can't just open a PR to add the route @dcodeIO ? :thinking: 

https://github.com/AssemblyScript/website/blob/master/src/.vuepress/config.js#L35

Would you be down to add the route in the dashboard, or send the email? Thanks! :smile:

**Comment by dcodeIO** [comment]
There isn't a whole lot I can configure within the DocSearch dashboard unfortunately. In fact, for OSS it appears to be mostly a minimal set of stats with no config whatsoever, and so far this seemed to be all automatic. Very strange. I remember reading something about it crawling the [Sitemap](https://www.assemblyscript.org/sitemap.xml) for example.

**Comment by dcodeIO** [comment]
Oh, wait, they mentioned this one in one of their emails: https://github.com/algolia/docsearch-configs/blob/master/configs/assemblyscript.json
Edit: Documentation for the file: https://docsearch.algolia.com/docs/config-file/

**Comment by dcodeIO** [comment]
PR: https://github.com/algolia/docsearch-configs/pull/2552

**Comment by dcodeIO** [comment]
Should be working now :)

**Comment by torch2424** [comment]
@dcodeIO Oops! Wasn't checking github over the weekend :upside_down_face: 

But! Thank you so much for fixing this! :smile: :tada: Stoked you were able to find a solution.

And I confirmed it works on the current site:

![Screenshot from 2020-10-19 11-17-57](https://user-images.githubusercontent.com/1448289/96495532-d8b36b80-11fc-11eb-9f41-1465d776d079.png)


Closing! Thanks again! :smile: :+1:
