### ISSUE TITLE
Offset param to load() and store() should be in elements and not bytes?

### ISSUE THREAD

**Issue by aduros** [AssemblyScript/website#97]
The pointer arithmetic example at https://www.assemblyscript.org/introduction.html#low-level-perspective seems incorrect:

```typescript
store<i32>(ptr, load<i32>(ptr) + load<i32>(ptr, 4), 8)
```

But to match the C example it should be:

```typescript
store<i32>(ptr, load<i32>(ptr) + load<i32>(ptr, 16), 32)
```

It looks like load/store offsets are implemented in bytes, but it would be really handy if it used the element size for parity with C.

**Comment by MaxGraey** [comment]
I moved this issue to website issues.
Regarding snippet. Yes it should be fixed but in C example:
```diff
- *(ptr + 8) = *ptr + *(ptr + 4)
+ *(ptr + 2) = *ptr + *(ptr + 1)
```
offsets should in bytes due to this wasm intrinsics and we can't change original semantics

PR is welcomed
